apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - port: 80              # Service port (inside cluster)
      targetPort: 8080      # Container port
      nodePort: 30080       # Optional (30000â€“32767)
